#!/bin/sh

deps=
for d in deps/* ; do
    deps="$deps -pa $d/ebin"
done
exec erl \
  -name erlrrd -setcookie erlrrd \
  $deps \
  -pa ebin \
  -config erlrrd_dev.config \
  -s reloader \
  -s erlrrd_app
