#!/usr/bin/env perl

local $| = 1;
while (defined($line = <ARGV>)) {
  chomp $line;

  if ($line =~ m/([^\s]+)\s(.*)/)
    {
      $cmd = $1;
      $rest = $2;
    }
  else
    {
      $cmd = $line;
      $rest = "";
    }

  if ($cmd eq "pwd") {
    print "ERROR: pwd disabled for testing\n";
  } elsif ($cmd eq "timeout") {
    sleep 1;
    print "ERROR: timed out\n";
  } elsif ($cmd eq "die") {
    print "OK u:0.01 s:0.02 r:0.03\n";
    exit 1;
  } elsif ($cmd eq "longresponse") {
    print "a234567890123456789012345678901234567890" x (255) . "\n";
    print "OK u:0.01 s:0.02 r:0.03\n";
  } else {
    print "$cmd $rest\n";
    print "OK u:0.01 s:0.02 r:0.03\n";
  }
}
0;
